@localhost=localhost:4004/odata/v4/main/
@id=73f695b2-72ce-4730-b35c-914832858b26

GET http://{{localhost}}/Customers
Content-Type: application/json

###

POST http://{{localhost}}/Customers
Content-Type: application/json

{
    "id": "{{id}}",
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com"
}

###

DELETE http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json

###

PATCH http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json

{
    "firstName": "Mark"
}

###

# Buscar todos os clientes que não terminam com '-5940057'
GET http://{{localhost}}/Customers?$filter=not endswith(firstName, '-5940057') and email eq 'email-4867866'
Content-Type: application/json

###

# Buscando dados com $search
GET http://{{localhost}}/Customers?$search=868
Content-Type: application/json

###

