@localhost=localhost:4004/odata/v4/main/
@id=3ac177dc-a55c-424c-8c4b-cfcf6fe9cfd5
@customerId=48678748-1c02-4712-9cf3-808ccae903c8
# produto sem estoque
@productId1=26013947-e95b-48b3-a5bb-1ef81ebdbaca
@productId2=26013947-e95b-48b3-a5bb-1ef81ebdbaca

GET http://{{localhost}}/SalesOrderHeaders?$filter=id eq {{id}}&$expand=items
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic cuka:Inicial@12345

{
    "id": "{{id}}",
    "customer_id": "{{customerId}}",
    "items": [
        {
            "id": "efd4dd0a-990b-404b-b49c-a256e420b3cf",
            "header_id": "{{id}}",
            "product_id": "{{productId1}}",
            "quantity": 10,
            "price": 2.99
        },
        {
            "id": "38d842f1-c347-4684-8ea2-080f6c235eba",
            "header_id": "{{id}}",
            "product_id": "{{productId2}}",
            "quantity": 5,
            "price": 1.99
        }
    ]
}

###

DELETE http://{{localhost}}/SalesOrderHeaders({{id}})
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345

###

PUT http://{{localhost}}/SalesOrderHeaders({{id}})
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345

{
    "modifiedBy": "teste"
}

###

# Buscar todos os pedidos maiores ou iguais a x valor
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 2000000
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345

###

# Expandir os itens do pedido, o cliente e expandir o produto do item
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount le 6000000&$expand=items($expand=product),customer
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345

###

# Expandir os itens do pedido, o cliente e expandir o produto do item e filtrar pela quantidade nos itens
GET http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product;$filter=quantity le 30),customer
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345
###

# Selecionar somente customer e id do sales order header e expandir o customer
GET http://{{localhost}}/SalesOrderHeaders?$select=id,customer&$expand=customer
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345

###

# Selecionar somente customer e id do sales order header e expandir o customer e selecionar somente o email do customer
GET http://{{localhost}}/SalesOrderHeaders?$select=id,customer&$expand=customer($select=email)
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345
###


# Descobrindo a quantidade de registros
GET http://{{localhost}}/SalesOrderHeaders/$count
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345
###

# Paginando os registros
GET http://{{localhost}}/SalesOrderHeaders?$skip=0&$top=5
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345

###

# Buscando dados com $search
GET http://{{localhost}}/SalesOrderHeaders?$search=cg7&$filter=totalAmount gt 500
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345

###

